specVersion: 1.0.0
name: webb-subql
version: 1.0.0
description: >-
  This project can be used as a starting point for developing your SubQuery
  project
repository: "https://github.com/subquery/subql-starter"
runner:
  node:
    name: "@subql/node"
    version: ">=1.0.0"
  query:
    name: "@subql/query"
    version: "*"

schema:
  file: ./schema.graphql

network:
  # Use Tangle network endpoint
  chainId: "0xa2514d34e63b81ffb056bcf07044c9e15552686c8793bf1bcd312de844698cde"
#  chainId: "0xe73defe42503251230e94a3dd29e3bb5d895d1f3370c132a833fcfb0d9b67c08"
  endpoint: "wss://stats-dev.api.webb.tools/public-ws" # using testnet endpoint
#  endpoint: "ws://host.docker.internal:9944" # using docker
# endpoint: "ws://127.0.0.1:9944" # not using docker

dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler

        - handler: handleEvent
          kind: substrate/EventHandler

        - handler: handleCall
          kind: substrate/CallHandler

        - handler: handleSudoCall
          kind: substrate/CallHandler
          filter:
            module: sudo
            method: sudo
            success: true

        - handler: handlePublicKeyChanged
          kind: substrate/EventHandler
          filter:
            module: dkg
            method: PublicKeyChanged

        - handler: handleAllDKG
          kind: substrate/EventHandler
          filter:
            module: dkgProposals

        - handler: handleAllDKG
          kind: substrate/EventHandler
          filter:
            module: dkg

        - handler: handleAllDKG
          kind: substrate/EventHandler
          filter:
            module: dkgProposalHandler

        - handler: handleIdentity
          kind: substrate/EventHandler
          filter:
            module: identity
            method: IdentitySet

        - handler: handleHeartbeats
          kind: substrate/EventHandler
          filter:
            module: imOnline
            method: HeartbeatReceived
