[store]
[store.primary]
connection = "postgresql://${postgres_user}:${postgres_pass}@${postgres_host}:5432/${postgres_db}"
pool_size = 10

[chains]
ingestor = "block_ingestor_node"

[chains.Athena]
shard = "primary"
provider = [{ label = "athena", url = "https://athena-testnet.webb.tools", features= ["archive", "traces"]}]

[chains.Hermes]
shard = "primary"
provider = [{ label = "hermes", url = "https://hermes-testnet.webb.tools", features= ["archive", "traces"]}]

[chains.Demeter]
shard = "primary"
provider = [{ label = "demeter", url = "https://demeter-testnet.webb.tools", features= ["archive", "traces"]}]

# [chains.Sepolia]
# shard = "primary"
# provider = [{ label = "sepolia", url = "https://sepolia.infura.io/v3/90de850aff68424ab8e7321017406586", features= []}]

[deployment]
shard = "primary"
[[deployment.rule]]
indexers = [ "default" ]