sources:
  - name: vanchor
    handler:
      graphql:
        endpoint: http://localhost:8000/subgraphs/name/{context.chainName:VAnchorAthenaLocal}

additionalTypeDefs: |
  extend type ShieldedTransaction {
    chainName: String!
  }

additionalResolvers:
  - ./src/resolvers.ts

documents:
  - ./example-queries/SchieldedTransactions.graphql

codegen:
  contextType: 'MeshContext & { chainName: string }'
