sources:
  - name: vanchor
    handler:
      graphql:
        # endpoint: '{context.subgraphUrl:http://localhost:8000/subgraphs/name/VAnchorOrbitAthena}' # for local development
        endpoint: '{context.subgraphUrl:https://thegraph-backend.webb.tools/subgraphs/name/VAnchorTangle}'

additionalTypeDefs: |
  extend type ShieldedTransaction {
    subgraphUrl: String!
  }

additionalResolvers:
  - ./src/resolvers.ts

codegen:
  contextType: 'MeshContext & { subgraphUrl: string }'

documents:
  - ./src/**/*.graphql
