sources:
  - name: vanchor
    handler:
      graphql:
        endpoint:
          {
            context.subgraphUrl:http://localhost:8000/subgraphs/name/VAnchorAthenaLocal,
          }

additionalTypeDefs: |
  extend type ShieldedTransaction {
    subgraphUrl: String!
  }

additionalResolvers:
  - ./src/resolvers.ts

codegen:
  contextType: 'MeshContext & { subgraphUrl: string }'
