import {
  GetVAnchorTotalValueLockedByChain,
  GetVAnchorTotalValueLockedByChains,
  GetVAnchorsTotalValueLockedByChain,
  GetVAnchorsTotalValueLockedByChains,
  GetVAnchorTotalValueLockedByChainAndByToken,
  GetVAnchorTotalValueLockedByChainsAndByToken,
  GetVAnchorTotalValueLockedByChain15MinsInterval,
  GetVAnchorTotalValueLockedByChains15MinsInterval,
  GetVAnchorsTotalValueLockedByChain15MinsInterval,
  GetVAnchorsTotalValueLockedByChains15MinsInterval,
  GetVAnchorTotalValueLockedByChainAndByToken15MinsInterval,
  GetVAnchorTotalValueLockedByChainsAndByToken15MinsInterval,
  GetVAnchorTotalValueLockedByChainByDay,
  GetVAnchorTotalValueLockedByChainsByDay,
  GetVAnchorsTotalValueLockedByChainByDay,
  GetVAnchorsTotalValueLockedByChainsByDay,
  GetVAnchorTotalValueLockedByChainAndByTokenByDay,
  GetVAnchorTotalValueLockedByChainsAndByTokenByDay,
  GetVAnchorsTVLByChainByDateRange,
  GetVAnchorsTVLByChainsByDateRange,
} from './queries/tvl';
import {
  GetVAnchorDepositByChain,
  GetVAnchorDepositByChains,
  GetVAnchorsDepositByChain,
  GetVAnchorsDepositByChains,
  GetVAnchorDepositByChainAndByToken,
  GetVAnchorDepositByChainsAndByToken,
  GetVAnchorDepositByChain15MinsInterval,
  GetVAnchorDepositByChains15MinsInterval,
  GetVAnchorsDepositByChain15MinsInterval,
  GetVAnchorsDepositByChains15MinsInterval,
  GetVAnchorDepositByChainAndByToken15MinsInterval,
  GetVAnchorDepositByChainsAndByToken15MinsInterval,
  GetVAnchorDepositByChainDayInterval,
  GetVAnchorDepositByChainsDayInterval,
  GetVAnchorsDepositByChainDayInterval,
  GetVAnchorsDepositByChainsDayInterval,
  GetVAnchorDepositByChainAndByTokenDayInterval,
  GetVAnchorDepositByChainsAndByTokenDayInterval,
  GetVAnchorsDepositByChainByDateRange,
  GetVAnchorsDepositByChainsByDateRange,
} from './queries/deposit';
import {
  GetVAnchorWithdrawalByChain,
  GetVAnchorWithdrawalByChains,
  GetVAnchorsWithdrawalByChain,
  GetVAnchorsWithdrawalByChains,
  GetVAnchorWithdrawalByChainAndByToken,
  GetVAnchorWithdrawalByChainsAndByToken,
  GetVAnchorWithdrawalByChain15MinsInterval,
  GetVAnchorWithdrawalByChains15MinsInterval,
  GetVAnchorsWithdrawalByChain15MinsInterval,
  GetVAnchorsWithdrawalByChains15MinsInterval,
  GetVAnchorWithdrawalByChainAndByToken15MinsInterval,
  GetVAnchorWithdrawalByChainsAndByToken15MinsInterval,
  GetVAnchorWithdrawalByChainDayInterval,
  GetVAnchorWithdrawalByChainsDayInterval,
  GetVAnchorsWithdrawalByChainDayInterval,
  GetVAnchorsWithdrawalByChainsDayInterval,
  GetVAnchorWithdrawalByChainAndByTokenDayInterval,
  GetVAnchorWithdrawalByChainsAndByTokenDayInterval,
  GetVAnchorsWithdrawalByChainByDateRange,
  GetVAnchorsWithdrawalByChainsByDateRange,
} from './queries/withdrawal';
import {
  GetVAnchorTotalRelayerFeeByChain,
  GetVAnchorTotalRelayerFeeByChainAndByToken,
  GetVAnchorsTotalRelayerFeeByChain,
  GetVAnchorsTotalRelayerFeeByChains,
} from './queries/RelayerFee';
import {
  GetVAnchorRelayerFeeByChainHistory,
  GetVAnchorRelayerFeeByChainAndByTokenHistory,
  GetVAnchorsRelayerFeeByChainHistory,
  GetVAnchorsRelayerFeeByChainsHistory,
} from './queries/RelayerFeeHistory';
import {
  GetVAnchorTotalWrappingFeeByChain,
  GetVAnchorTotalWrappingFeeByChainAndByToken,
  GetVAnchorsTotalWrappingFeeByChain,
  GetVAnchorsTotalWrappingFeeByChains,
} from './queries/WrappingFee';
import {
  GetVAnchorWrappingFeeByChainHistory,
  GetVAnchorWrappingFeeByChainAndByTokenHistory,
  GetVAnchorsWrappingFeeByChainHistory,
  GetVAnchorsWrappingFeeByChainsHistory,
} from './queries/WrappingFeeHistory';
import { SubgraphUrl } from './config';

const vAnchorClient = {
  SubgraphUrl,
  RelayerFee: {
    GetVAnchorTotalRelayerFeeByChain,
    GetVAnchorTotalRelayerFeeByChainAndByToken,
    GetVAnchorsTotalRelayerFeeByChain,
    GetVAnchorsTotalRelayerFeeByChains,
  },
  RelayerFeeHistory: {
    GetVAnchorRelayerFeeByChainHistory,
    GetVAnchorRelayerFeeByChainAndByTokenHistory,
    GetVAnchorsRelayerFeeByChainHistory,
    GetVAnchorsRelayerFeeByChainsHistory,
  },
  WrappingFee: {
    GetVAnchorTotalWrappingFeeByChain,
    GetVAnchorTotalWrappingFeeByChainAndByToken,
    GetVAnchorsTotalWrappingFeeByChain,
    GetVAnchorsTotalWrappingFeeByChains,
  },
  WrappingFeeHistory: {
    GetVAnchorWrappingFeeByChainHistory,
    GetVAnchorWrappingFeeByChainAndByTokenHistory,
    GetVAnchorsWrappingFeeByChainHistory,
    GetVAnchorsWrappingFeeByChainsHistory,
  },
  Deposit: {
    GetVAnchorDepositByChain,
    GetVAnchorDepositByChains,
    GetVAnchorsDepositByChain,
    GetVAnchorsDepositByChains,
    GetVAnchorDepositByChainAndByToken,
    GetVAnchorDepositByChainsAndByToken,
    GetVAnchorDepositByChain15MinsInterval,
    GetVAnchorDepositByChains15MinsInterval,
    GetVAnchorsDepositByChain15MinsInterval,
    GetVAnchorsDepositByChains15MinsInterval,
    GetVAnchorDepositByChainAndByToken15MinsInterval,
    GetVAnchorDepositByChainsAndByToken15MinsInterval,
    GetVAnchorDepositByChainDayInterval,
    GetVAnchorDepositByChainsDayInterval,
    GetVAnchorsDepositByChainDayInterval,
    GetVAnchorsDepositByChainsDayInterval,
    GetVAnchorDepositByChainAndByTokenDayInterval,
    GetVAnchorDepositByChainsAndByTokenDayInterval,
    GetVAnchorsDepositByChainByDateRange,
    GetVAnchorsDepositByChainsByDateRange,
  },
  Withdrawal: {
    GetVAnchorWithdrawalByChain,
    GetVAnchorWithdrawalByChains,
    GetVAnchorsWithdrawalByChain,
    GetVAnchorsWithdrawalByChains,
    GetVAnchorWithdrawalByChainAndByToken,
    GetVAnchorWithdrawalByChainsAndByToken,
    GetVAnchorWithdrawalByChain15MinsInterval,
    GetVAnchorWithdrawalByChains15MinsInterval,
    GetVAnchorsWithdrawalByChain15MinsInterval,
    GetVAnchorsWithdrawalByChains15MinsInterval,
    GetVAnchorWithdrawalByChainAndByToken15MinsInterval,
    GetVAnchorWithdrawalByChainsAndByToken15MinsInterval,
    GetVAnchorWithdrawalByChainDayInterval,
    GetVAnchorWithdrawalByChainsDayInterval,
    GetVAnchorsWithdrawalByChainDayInterval,
    GetVAnchorsWithdrawalByChainsDayInterval,
    GetVAnchorWithdrawalByChainAndByTokenDayInterval,
    GetVAnchorWithdrawalByChainsAndByTokenDayInterval,
    GetVAnchorsWithdrawalByChainByDateRange,
    GetVAnchorsWithdrawalByChainsByDateRange,
  },
  TotalValueLocked: {
    GetVAnchorTotalValueLockedByChain,
    GetVAnchorTotalValueLockedByChains,
    GetVAnchorsTotalValueLockedByChain,
    GetVAnchorsTotalValueLockedByChains,
    GetVAnchorTotalValueLockedByChainAndByToken,
    GetVAnchorTotalValueLockedByChainsAndByToken,
    GetVAnchorTotalValueLockedByChain15MinsInterval,
    GetVAnchorTotalValueLockedByChains15MinsInterval,
    GetVAnchorsTotalValueLockedByChain15MinsInterval,
    GetVAnchorsTotalValueLockedByChains15MinsInterval,
    GetVAnchorTotalValueLockedByChainAndByToken15MinsInterval,
    GetVAnchorTotalValueLockedByChainsAndByToken15MinsInterval,
    GetVAnchorTotalValueLockedByChainByDay,
    GetVAnchorTotalValueLockedByChainsByDay,
    GetVAnchorsTotalValueLockedByChainByDay,
    GetVAnchorsTotalValueLockedByChainsByDay,
    GetVAnchorTotalValueLockedByChainAndByTokenByDay,
    GetVAnchorTotalValueLockedByChainsAndByTokenByDay,
    GetVAnchorsTVLByChainByDateRange,
    GetVAnchorsTVLByChainsByDateRange,
  },
};

export default vAnchorClient;
