specVersion: 1.0.0
name: webb-subql
version: 1.0.0
description: >-
  This project can be used as a starting point for developing your SubQuery
  project
repository: 'https://github.com/subquery/subql-starter'
runner:
  node:
    name: '@subql/node'
    version: '=v1.21.1'
  query:
    name: '@subql/query'
    version: '*'

schema:
  file: ./schema.graphql

network:
  # Use Tangle network endpoint for Arana Alpha testnet see: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fstats-dev.api.webb.tools%2Fpublic-ws#/settings/metadata
  chainId: '0xd2376c35c81de72d4d5914fc2800e81cfcb2e08dd936f7012df1349988cd3502'
  # using testnet archive node endpoint
  # endpoint: 'wss://tangle-standalone-archive.webb.tools/'
  # if you are using docker, uncomment the below line
  endpoint: 'ws://host.docker.internal:9944'
  # if you are not using Docker and want to run locally, uncomment the below line
  # endpoint: 'ws://127.0.0.1:9944'

dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler

        - handler: handleEvent
          kind: substrate/EventHandler

        - handler: handleCall
          kind: substrate/CallHandler

        - handler: handleSudoCall
          kind: substrate/CallHandler
          filter:
            module: sudo
            method: sudo
            success: true

        - handler: handlePublicKeyChanged
          kind: substrate/EventHandler
          filter:
            module: dkg
            method: PublicKeyChanged

        - handler: handleAllDKG
          kind: substrate/EventHandler
          filter:
            module: dkgProposals

        - handler: handleAllDKG
          kind: substrate/EventHandler
          filter:
            module: dkg

        - handler: handleAllDKG
          kind: substrate/EventHandler
          filter:
            module: dkgProposalHandler

        - handler: handleIdentity
          kind: substrate/EventHandler
          filter:
            module: identity
            method: IdentitySet

        - handler: handleHeartbeats
          kind: substrate/EventHandler
          filter:
            module: imOnline
            method: HeartbeatReceived
