name: ts-check ✅
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: ['main', 'feat/**', 'feature/**']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dkg:
    name: dkg
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: dkg
        run: |
          yarn install
          cd packages/dkg && yarn install && yarn codegen && yarn ts-check

  tangle-mainnet:
    name: tangle-mainnet
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: tangle-mainnet
        run: |
          yarn install
          cd packages/tangle-mainnet && yarn install && yarn codegen && yarn ts-check

  # add vanchor (running ts-check in vanchor package is not ready yet)

  vanchor-client:
    name: vanchor-client
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: vanchor-client
        run: |
          yarn install
          cd packages/vanchor-client && yarn install && yarn build && yarn ts-check
