name: lint 🧹
on:
  # Temporay disable linting as we need to select one tool for managing mono-repo (nx or lerna)
  # Depends on https://github.com/webb-tools/webb-graphql/issues/132
  # push:
  #   branches:
  #     - 'main'
  # pull_request:
  #   branches:
  #     - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: lint
        run: |
          yarn install
          yarn run format && yarn run lint
